// Generated by Wrangler by running `wrangler types`

/**
 * Environment bindings for the Worker script.
 * @interface
 */
interface Env {
	PROMPTS: DurableObjectNamespace<import("./src/index").PromptsDurableObject>;
	RL_PUBLISH_FEED: Queue;
	RL_SUMMARIZE: Queue;
}
